version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/video-analysis
      - JWT_SECRET=your-secret-key
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 